FROM node:18-alpine

# Install FFMPEG and heavy dependencies for media processing
RUN apk add --no-cache ffmpeg python3 make g++

WORKDIR /app

COPY package*.json ./
RUN npm ci --only=production

COPY . .

# Set FFMPEG Path for Fluent-FFMPEG
ENV FFMPEG_PATH=/usr/bin/ffmpeg

CMD ["node", "src/workerEntry.js"]
