const fs = require('fs');
const path = require('path');

const rootEnvPath = path.join(__dirname, '..', '.env');
const dashboardEnvPath = path.join(__dirname, '..', 'web-dashboard', '.env.local');

// Keys that should be synced to frontend
// Maps Backend Key -> Frontend Key (if different, or same if null)
const SYNC_KEYS = {
    'EVOLUTION_API_URL': 'NEXT_PUBLIC_EVOLUTION_API_URL',
    'EVOLUTION_API_KEY': 'NEXT_PUBLIC_EVOLUTION_API_KEY',
    'SUPABASE_URL': 'NEXT_PUBLIC_SUPABASE_URL',
    'SUPABASE_ANON_KEY': 'NEXT_PUBLIC_SUPABASE_ANON_KEY',
    'INTERNAL_WEBHOOK_URL': 'INTERNAL_WEBHOOK_URL', // Keep as is for server-side usage in Next.js
    'SUPABASE_SERVICE_ROLE_KEY': 'SUPABASE_SERVICE_ROLE_KEY' // Keep as is
};

function parseEnv(filePath) {
    if (!fs.existsSync(filePath)) return {};
    const content = fs.readFileSync(filePath, 'utf8');
    const env = {};
    // Handle different line endings
    const lines = content.split(/\r?\n/);
    lines.forEach(line => {
        line = line.trim();
        if (!line || line.startsWith('#')) return; // Skip empty or comments

        const match = line.match(/^([^=]+)=(.*)$/);
        if (match) {
            const key = match[1].trim();
            const value = match[2].trim();
            env[key] = value;
        }
    });
    return env;
}

function syncEnv() {
    const logFile = path.join(__dirname, '..', 'sync_debug.log');
    const log = (msg) => {
        fs.appendFileSync(logFile, msg + '\n');
        process.stdout.write(msg + '\n'); // Also print to stdout
    };

    // Clear previous log
    if (fs.existsSync(logFile)) fs.unlinkSync(logFile);

    log('🔄 Syncing .env to web-dashboard/.env.local...');
    log('📂 Root .env path: ' + rootEnvPath);

    const rootEnv = parseEnv(rootEnvPath);
    log(`🔍 Found ${Object.keys(rootEnv).length} keys in root .env: ${Object.keys(rootEnv).join(', ')}`);

    const validLines = [];

    // Header
    validLines.push('# --- AUTO-GENERATED BY scripts/sync_env.js ---');
    validLines.push(`# Last Sync: ${new Date().toISOString()}`);
    validLines.push('');

    let syncedCount = 0;

    Object.entries(SYNC_KEYS).forEach(([backendKey, frontendKey]) => {
        const value = rootEnv[backendKey];
        if (value) {
            validLines.push(`${frontendKey}=${value}`);
            syncedCount++;
        } else {
            log(`⚠️ Warning: Key ${backendKey} not found in root .env`);
        }
    });

    const content = validLines.join('\n') + '\n';
    fs.writeFileSync(dashboardEnvPath, content);

    log(`✅ Synced ${syncedCount} keys to ${dashboardEnvPath}`);
}

syncEnv();
